name: My_GitHub_Actions

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on:   
      labels:
      
    steps:
      name: Print Hello Message
      run: echo "Hello World"

  my_deploy:
    runs-on:   
      labels:
    needs: my_testing
      
    steps:
      name: Print Hello Message
      run: echo "Hello World"
